# Generated by Django 3.0.4 on 2021-10-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(blank=True, max_length=20, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('impression', models.IntegerField(blank=True, null=True)),
                ('ctr', models.DecimalField(blank=True, decimal_places=30, max_digits=100)),
                ('position', models.DecimalField(blank=True, decimal_places=30, max_digits=100)),
            ],
        ),
    ]
