# Generated by Django 3.0.4 on 2021-10-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211015_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='ctr',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=100),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='position',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=100),
        ),
    ]
